### ISSUE TITLE
Add your first solution to any question

### ISSUE THREAD

**Issue by burninghell2002** [burninghell2002/competitive_solution#3]

**Comment by devsingh1234** [comment]
I WILL LIKE TO DO THIS WORK I AM A TOTAL BIGNNER

**Comment by abhinitrpr** [comment]
I would like to do this

**Comment by chehak123** [comment]
I would like to work on this

**Comment by burninghell2002** [comment]
Okay go ahead!!

**Comment by dikshantmali** [comment]
I also want to work on this issue
please assign it to me as well. and please tell me in which directory should  I add my solution like Leetcode/dikshant is fine

**Comment by dikshantmali** [comment]
Can I use c++ language? to add solution

**Comment by dikshantmali** [comment]
I have made a pull request, please verify and merge it

**Comment by RiyaGoel27** [comment]
Hi , I would also like to work on this

**Comment by RiyaGoel27** [comment]
Can I also work on this?

**Comment by Riyagoel2** [comment]
Hi , I am sorry I used the wrong id . Can you please reassign me  . I'll delete the previous comment

**Comment by codeshruti** [comment]
I want to work on this issue. Please assign this to me.

**Comment by burninghell2002** [comment]
@dikshantmali yes you can do that

**Comment by Manoj13-coder** [comment]
May i add more competitive questions ?

**Comment by JINDAL-JJ** [comment]
I would also like to add some of my codechef solutions in cpp.

**Comment by Sindhu-321** [comment]
If the issue is still open may i give it a try? I would like to add some c++ solutions to some codeforces problems. Thanks!
